# Generated by Django 3.1.7 on 2022-05-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20220508_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgurl',
            field=models.TextField(default='about:blank', max_length=1000),
            preserve_default=False,
        ),
    ]
